Rails.application.routes.draw do
  resources :orders, only: [:create]
  resources :products, only: [:index, :create, :new]
  resources :restaurants
  devise_for :users
  root to: 'home#index'
  # get 'home/index' // Generated by command: rails g controller home index
end
